/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DaftarMenu.java
 *
 * Created on 27-Mar-2018, 19:33:08
 */
package Menu;

/**
 *
 * @author MSI
 */
public class DaftarMenu extends javax.swing.JFrame {

    /** Creates new form DaftarMenu */
    public DaftarMenu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboxNasiGoreng = new javax.swing.JLabel();
        cboxAyamBakar = new javax.swing.JLabel();
        cboxAyamGeprek = new javax.swing.JLabel();
        cboxNasi = new javax.swing.JLabel();
        cboxAyamSayur = new javax.swing.JLabel();
        cboxTehManis = new javax.swing.JLabel();
        cboxJeruk = new javax.swing.JLabel();
        cboxMangga = new javax.swing.JLabel();
        cboxMelon = new javax.swing.JLabel();
        cboxAlpukat = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtJlhNasiGoreng = new javax.swing.JTextField();
        txtJlhAyamBakar = new javax.swing.JTextField();
        txtJlhAyamGeprek = new javax.swing.JTextField();
        txtJlhNasi = new javax.swing.JTextField();
        txtJlhAyamSayur = new javax.swing.JTextField();
        txtJlhTehManis = new javax.swing.JTextField();
        txtJlhJeruk = new javax.swing.JTextField();
        txtJlhMangga = new javax.swing.JTextField();
        txtJlhAlpukat = new javax.swing.JTextField();
        txtJlhMelon = new javax.swing.JTextField();
        lblTHrgNasiGoreng = new javax.swing.JLabel();
        lblTHrgAyamBakar = new javax.swing.JLabel();
        lblTHrgAyamGeprek = new javax.swing.JLabel();
        lblTHrgNasi = new javax.swing.JLabel();
        lblTHrgAyamSayur = new javax.swing.JLabel();
        lblTHrgTehManis = new javax.swing.JLabel();
        lblTHrgJeruk = new javax.swing.JLabel();
        lblTHrgMangga = new javax.swing.JLabel();
        lblTHrgMelon = new javax.swing.JLabel();
        lblTHrgAlpukat = new javax.swing.JLabel();
        lblTJlh = new javax.swing.JLabel();
        lblTBayar = new javax.swing.JLabel();
        TOTAL = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("Salman Suranta Cafe's ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Menu");

        jLabel3.setText("Qty");

        jLabel4.setText("Total Harga");

        jLabel5.setText("Makanan");

        jLabel6.setText("Minuman");

        cboxNasiGoreng.setText("Nasi Goreng");

        cboxAyamBakar.setText("Ayam bakar");

        cboxAyamGeprek.setText("Ayam geprek");

        cboxNasi.setText("Nasi");

        cboxAyamSayur.setText("Ayam sayur");

        cboxTehManis.setText("Es teh manis");

        cboxJeruk.setText("Es jeruk");

        cboxMangga.setText("Jus mangga");

        cboxMelon.setText("Jus melon");

        cboxAlpukat.setText("Jus alpukat");

        jLabel20.setText("12000");

        jLabel21.setText("15000");

        jLabel22.setText("12000");

        jLabel23.setText("5000");

        jLabel24.setText("10000");

        jLabel25.setText("5000");

        jLabel26.setText("10000");

        jLabel27.setText("10000");

        jLabel28.setText("10000");

        jLabel29.setText("10000");

        lblTHrgNasiGoreng.setText("Rp.0,-");

        lblTHrgAyamBakar.setText("Rp.0,-");

        lblTHrgAyamGeprek.setText("Rp.0,-");

        lblTHrgNasi.setText("Rp.0,-");

        lblTHrgAyamSayur.setText("Rp.0,-");

        lblTHrgTehManis.setText("Rp.0,-");

        lblTHrgJeruk.setText("Rp.0,-");

        lblTHrgMangga.setText("Rp.0,-");

        lblTHrgMelon.setText("Rp.0,-");

        lblTHrgAlpukat.setText("Rp.0,-");

        lblTJlh.setText("0 Porsi");

        lblTBayar.setText("Rp.0,-");

        TOTAL.setText("Total Bayar");

        jButton1.setText("Hitung");

        jButton2.setText("Reset");

        jButton3.setText("Keluar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(629, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(189, 189, 189)
                .addComponent(jLabel4)
                .addGap(104, 104, 104))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TOTAL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 559, Short.MAX_VALUE)
                        .addComponent(lblTJlh)
                        .addGap(194, 194, 194)
                        .addComponent(lblTBayar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(398, 398, 398)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxAlpukat)
                                    .addComponent(cboxMelon)
                                    .addComponent(cboxMangga)
                                    .addComponent(cboxJeruk)
                                    .addComponent(cboxTehManis)
                                    .addComponent(cboxAyamSayur)
                                    .addComponent(cboxNasi)
                                    .addComponent(cboxAyamGeprek)
                                    .addComponent(cboxAyamBakar)
                                    .addComponent(cboxNasiGoreng))))
                        .addGap(176, 176, 176)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJlhAyamSayur, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txtJlhNasiGoreng, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txtJlhAyamBakar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txtJlhAyamGeprek, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txtJlhNasi, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txtJlhTehManis, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txtJlhJeruk, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txtJlhMangga, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txtJlhMelon, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txtJlhAlpukat, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTHrgTehManis, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTHrgJeruk, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTHrgMangga, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTHrgMelon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTHrgAlpukat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTHrgNasiGoreng, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTHrgAyamSayur, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTHrgNasi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTHrgAyamGeprek, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTHrgAyamBakar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(104, 104, 104)
                        .addComponent(jButton2)
                        .addGap(107, 107, 107)
                        .addComponent(jButton3)))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboxNasiGoreng)
                    .addComponent(jLabel20)
                    .addComponent(lblTHrgNasiGoreng)
                    .addComponent(txtJlhNasiGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxAyamBakar)
                    .addComponent(jLabel21)
                    .addComponent(lblTHrgAyamBakar)
                    .addComponent(txtJlhAyamBakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxAyamGeprek)
                    .addComponent(jLabel22)
                    .addComponent(lblTHrgAyamGeprek)
                    .addComponent(txtJlhAyamGeprek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxNasi)
                    .addComponent(jLabel23)
                    .addComponent(lblTHrgNasi)
                    .addComponent(txtJlhNasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxAyamSayur)
                    .addComponent(jLabel24)
                    .addComponent(lblTHrgAyamSayur)
                    .addComponent(txtJlhAyamSayur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboxTehManis)
                    .addComponent(jLabel25)
                    .addComponent(lblTHrgTehManis)
                    .addComponent(txtJlhTehManis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxJeruk)
                    .addComponent(jLabel26)
                    .addComponent(lblTHrgJeruk)
                    .addComponent(txtJlhJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxMangga)
                    .addComponent(jLabel27)
                    .addComponent(lblTHrgMangga)
                    .addComponent(txtJlhMangga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxMelon)
                    .addComponent(jLabel28)
                    .addComponent(lblTHrgMelon)
                    .addComponent(txtJlhMelon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxAlpukat)
                    .addComponent(jLabel29)
                    .addComponent(lblTHrgAlpukat)
                    .addComponent(txtJlhAlpukat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTJlh)
                    .addComponent(lblTBayar)
                    .addComponent(TOTAL))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DaftarMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TOTAL;
    private javax.swing.JLabel cboxAlpukat;
    private javax.swing.JLabel cboxAyamBakar;
    private javax.swing.JLabel cboxAyamGeprek;
    private javax.swing.JLabel cboxAyamSayur;
    private javax.swing.JLabel cboxJeruk;
    private javax.swing.JLabel cboxMangga;
    private javax.swing.JLabel cboxMelon;
    private javax.swing.JLabel cboxNasi;
    private javax.swing.JLabel cboxNasiGoreng;
    private javax.swing.JLabel cboxTehManis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblTBayar;
    private javax.swing.JLabel lblTHrgAlpukat;
    private javax.swing.JLabel lblTHrgAyamBakar;
    private javax.swing.JLabel lblTHrgAyamGeprek;
    private javax.swing.JLabel lblTHrgAyamSayur;
    private javax.swing.JLabel lblTHrgJeruk;
    private javax.swing.JLabel lblTHrgMangga;
    private javax.swing.JLabel lblTHrgMelon;
    private javax.swing.JLabel lblTHrgNasi;
    private javax.swing.JLabel lblTHrgNasiGoreng;
    private javax.swing.JLabel lblTHrgTehManis;
    private javax.swing.JLabel lblTJlh;
    private javax.swing.JTextField txtJlhAlpukat;
    private javax.swing.JTextField txtJlhAyamBakar;
    private javax.swing.JTextField txtJlhAyamGeprek;
    private javax.swing.JTextField txtJlhAyamSayur;
    private javax.swing.JTextField txtJlhJeruk;
    private javax.swing.JTextField txtJlhMangga;
    private javax.swing.JTextField txtJlhMelon;
    private javax.swing.JTextField txtJlhNasi;
    private javax.swing.JTextField txtJlhNasiGoreng;
    private javax.swing.JTextField txtJlhTehManis;
    // End of variables declaration//GEN-END:variables
}
